# Stage 1: Build the Angular app
FROM node:20-slim AS build
WORKDIR /app
COPY client/ .
RUN npm install
RUN npm run build --prod

# Stage 2: Serve the app with Nginx
FROM nginx:alpine
COPY --from=build /app/dist/client /usr/share/nginx/html
COPY client/nginx.conf /etc/nginx/conf.d/default.conf
