# Stage 1: Build
FROM node:20-slim AS build
WORKDIR /app
COPY client/package*.json ./
RUN npm install
COPY client/ ./
RUN npm run build --prod

FROM nginx:alpine

RUN rm -rf /etc/nginx/conf.d/* && \
    rm -rf /usr/share/nginx/html/*

COPY client/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist/client/browser/. /usr/share/nginx/html/

RUN ls -la /usr/share/nginx/html